name: Auto-sync Figma Tokens

on:
  repository_dispatch:
    types: [figma-tokens-update, tokens-updated]
  push:
    paths:
      - 'tokens/**/*.json'
    branches: [production]
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force sync tokens'
        required: false
        default: 'false'

jobs:
  sync-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Deploy to GitHub Pages
        run: |
          npm run build
        
      - name: Deploy to GitHub Pages
        if: steps.changes.outputs.changed == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
